stages:
  - deployment
  - build
  - tests

variables:
  $DOCKER_AUTH_CONFIG: karimogr

build:
  stage: build
  runs-on: self-hosted
  script:
    - ls
    - echo "Building application..."
    - cd api
    - mvn package
    - rake

tests:
  stage: tests
  runs-on: self-hosted
  script:
    - echo "Run unit tests..."
    - mvn test

deployment:
  stage: deployment
  runs-on: self-hosted
  script:
    - docker login
    - sudo -s docker-compose down
    - sudo -s docker-compose up 
